SERVER_IP = 'localhost'
SERVER_PORT = 30000
SERVER_ADDR = (SERVER_IP, SERVER_PORT)

CLIENT_IP = 'localhost'
CLIENT_PORT = 20000
CLIENT_ADDR = (CLIENT_IP, CLIENT_PORT)

HEADER_FORMAT = "HHBBHH"
HEADER_SIZE = 10
PAYLOAD_SIZE = 1008
SEGMENT_SIZE = HEADER_SIZE + PAYLOAD_SIZE
ENCODING = "utf-8"
